CREATE TABLE Stores (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    StoreCode NVARCHAR(50) NOT NULL UNIQUE,
    StoreName NVARCHAR(255) NOT NULL,
    Address NVARCHAR(500) NOT NULL,
    Phone NVARCHAR(20) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NULL
);
