import json

translations = {
    "Employee not found.": "Không tìm thấy nhân viên.",
    "Employee updated.": "Đã cập nhật nhân viên.",
    "End": "Kết thúc",
    "End shift": "Kết thúc ca",
    "Enter amount...": "Nhập số lượng...",
    "Enter category name to search...": "Nhập tên danh mục để tìm kiếm...",
    "Error": "Lỗi",
    "Error creating receipt: ": "Lỗi tạo phiếu: ",
    "Error deleting customer: ": "Lỗi xóa khách hàng: ",
    "Error deleting. Record might be in use.": "Lỗi xóa. Bản ghi có thể đang được sử dụng.",
    "Error deleting: ": "Lỗi xóa: ",
    "Error exporting Excel: ": "Lỗi xuất Excel: ",
    "Error loading accounts: ": "Lỗi tải tài khoản: ",
    "Error loading data: ": "Lỗi tải dữ liệu: ",
    "Error loading details: ": "Lỗi tải chi tiết: ",
    "Error saving data: ": "Lỗi lưu dữ liệu: ",
    "Error: ": "Lỗi: ",
    "Excel file exported successfully!": "Xuất file Excel thành công!",
    "Export": "Xuất kho",
    "Export Excel": "Xuất Excel",
    "Export PDF": "Xuất PDF",
    "Export Receipt Details": "Chi tiết phiếu xuất",
    "FULL NAME": "HỌ VÀ TÊN",
    "Feature under development!": "Tính năng đang được phát triển!",
    "Filter": "Lọc",
    "Filter data...": "Lọc dữ liệu...",
    "Forgot Password?": "Quên mật khẩu?",
    "Form1": "Form1",
    "General statistics": "Thống kê chung",
    "Group": "Nhóm",
    "Healthy": "Bình thường",
    "INVOICE DETAILS": "CHI TIẾT HÓA ĐƠN",
    "ISBN": "ISBN",
    "ISBN: ": "ISBN: ",
    "Import (Goods Inward)": "Nhập hàng",
    "Import Receipt Details": "Chi tiết phiếu nhập",
    "In stock": "Còn hàng",
    "Info": "Thông tin",
    "Information": "Thông tin",
    "Input error": "Lỗi nhập liệu",
    "Invalid opening cash amount.": "Số tiền đầu ca không hợp lệ.",
    "Invalid username or password.": "Tên đăng nhập hoặc mật khẩu không đúng.",
    "Inventory info saved successfully!": "Đã lưu thông tin kho thành công!",
    "Inventory management": "Quản lý kho",
    "Inventory statistics": "Thống kê kho",
    "Invoice Details": "Chi tiết hóa đơn",
    "Invoice ID / Customer Phone": "Mã Hóa đơn / SĐT",
    "Invoice Management": "Quản lý hóa đơn",
    "Invoice details not found.": "Không tìm thấy chi tiết hóa đơn.",
    "Invoice history": "Lịch sử hóa đơn",
    "Invoice info": "Thông tin hóa đơn",
    "Invoice not found.": "Không tìm thấy hóa đơn.",
    "Is Active": "Đang hoạt động",
    "Kho": "Kho",
    "LOGGED IN": "ĐÃ ĐĂNG NHẬP",
    "Last automated backup completed successfully today at 02:00 AM.": "Bản sao lưu tự động hoàn thành thành công hôm nay lúc 02:00 SA.",
    "List of all orders from customers.": "Danh sách tất cả các đơn hàng.",
    "Locked": "Đã khóa",
    "Lookup inventory": "Tra cứu tồn kho",
    "Low Stock Products": "Sản phẩm sắp hết hàng",
    "Low Stock Threshold": "Mức cảnh báo sắp hết",
    "MANAGER": "NGƯỜI QUẢN LÝ",
    "Manage admin and staff access permissions.": "Quản lý quyền truy cập Admin và nhân viên.",
    "Manage and classify books in the system.": "Quản lý và phân loại sách.",
    "Manage author list": "Quản lý danh sách tác giả",
    "Manage authors' info and works.": "Quản lý thông tin và tác phẩm tác giả.",
    "Manage book categories": "Quản lý danh mục sách",
    "Manage books, inventory, and book information.": "Quản lý sách, tồn kho, và thông tin sách.",
    "Manage bookstore locations, personnel, and operational status.": "Quản lý chi nhánh, nhân sự, và trạng thái.",
    "Manage core configuration, security, and operational parameters.": "Quản lý cấu hình, bảo mật, và hệ thống.",
    "Manage customer info, reward points and status.": "Quản lý khách hàng, điểm thưởng và trạng thái.",
    "Manage export receipts and track goods leaving the inventory.": "Quản lý phiếu xuất và theo dõi xuất kho.",
    "Manage master data": "Quản lý dữ liệu gốc",
    "Manage partner publishers list.": "Quản lý danh sách NXB đối tác.",
    "Manage publisher list": "Quản lý danh sách Nhà xuất bản",
    "Manage purchase receipts and goods imported from suppliers.": "Quản lý phiếu nhập và hàng hóa nhập.",
    "Manage return receipts and refund requests.": "Quản lý phiếu trả và yêu cầu hoàn tiền.",
    "Manage staff records, roles, and branch assignments.": "Quản lý nhân viên, vai trò, và chi nhánh.",
    "Manage supplier information and contacts.": "Quản lý thông tin liên hệ nhà cung cấp.",
    "Management System Login": "Đăng Nhập Hệ Thống Quản Lý",
    "Manager Name": "Tên Người quản lý",
    "Min": "Tối thiểu",
    "Min stock": "Tồn tối thiểu",
    "My shifts": "Ca của tôi",
    "NATIONALITY": "QUỐC TỊCH",
    "Name": "Tên",
    "Nationality": "Quốc tịch",
    "No data": "Không có dữ liệu",
    "No shift available": "Không có ca",
    "Not enough stock!": "Không đủ tồn kho!",
    "ORIGINAL ORDER ID": "MÃ ĐƠN GỐC",
    "Opening cash (VND)": "Tiền mặt đầu ca (VND)",
    "Order ID (*):": "Mã đơn hàng (*):",
    "Order Management": "Quản lý Đơn hàng",
    "Order cancellation error: ": "Lỗi hủy đơn: ",
    "Order cancelled successfully.": "Hủy đơn hàng thành công.",
    "Order not found or empty!": "Không tìm thấy đơn hàng hoặc đơn hàng trống!",
    "Out of stock": "Hết hàng",
    "Overview and analysis of current inventory data.": "Tổng quan và phân tích dữ liệu kho hiện tại.",
    "Overview of revenue, orders and low stock warnings.": "Tổng quan doanh thu, đơn hàng và cảnh báo kho.",
    "PHONE": "ĐIỆN THOẠI",
    "PHONE NUMBER": "SỐ ĐIỆN THOẠI",
    "POSITION": "VỊ TRÍ",
    "PRODUCT DETAILS": "CHI TIẾT SẢN PHẨM",
    "PUBLISHER ID": "MÃ NXB",
    "PUBLISHER NAME": "TÊN NXB",
    "Password": "Mật khẩu",
    "Password (Leave blank if not changing)": "Mật khẩu (Để trống nếu không đổi)",
    "Password (Leave blank if unchanged)": "Mật khẩu (Để trống nếu không đổi)",
    "Password is required for new employee.": "Vui lòng nhập mật khẩu cho nhân viên mới.",
    "Pay (F9)": "Thanh toán (F9)",
    "Payment": "Thanh toán",
    "Payment successful!": "Thanh toán thành công!",
    "Payroll": "Tính lương",
    "Payroll feature is under development.": "Tính năng tính lương đang phát triển.",
    "Phone Number": "Số điện thoại",
    "Phone number": "Số điện thoại",
    "Please enter a numeric Order ID!": "Vui lòng nhập Mã đơn hàng dạng số!",
    "Please enter author name!": "Vui lòng nhập tên tác giả!",
    "Please enter barcode.": "Vui lòng nhập mã vạch.",
    "Please enter customer's full name.": "Vui lòng nhập họ tên khách hàng.",
    "Please enter name!": "Vui lòng nhập tên!",
    "Please enter password for new account.": "Vui lòng nhập mật khẩu cho tài khoản mới.",
    "Please enter publisher name!": "Vui lòng nhập tên NXB!",
    "Please enter return quantity for at least one item.": "Vui lòng nhập số lượng trả cho ít nhất một mặt hàng.",
    "Please enter supplier name!": "Vui lòng nhập tên nhà cung cấp!",
    "Please enter username and password.": "Vui lòng nhập tài khoản và mật khẩu.",
    "Please fill required fields (*).": "Vui lòng điền các trường bắt buộc (*).",
    "Please select a shift.": "Vui lòng chọn một ca.",
    "Price: ": "Giá: ",
    "Print Invoice": "In Hóa đơn",
    "Print List": "In Danh sách",
    "Product": "Sản phẩm",
    "Product List": "Danh sách Sản phẩm",
    "Product details:": "Chi tiết sản phẩm:",
    "Publisher": "Nhà xuất bản",
    "Publisher ID": "Mã NXB",
    "Publisher Management": "Quản lý Nhà xuất bản",
    "Publisher Name": "Tên NXB",
    "Publisher data not found!": "Không tìm thấy dữ liệu NXB!",
    "Publisher management": "Quản lý nhà xuất bản",
    "Publisher name (*)": "Tên NXB (*)",
    "Publisher name already exists!": "Tên NXB đã tồn tại!",
    "Publisher: ": "NXB: ",
    "Q": "Q",
    "REASON": "LÝ DO",
    "REFUND AMOUNT": "SỐ TIỀN HOÀN",
    "REQUEST DATE": "NGÀY YÊU CẦU",
    "RETURN ID": "MÃ TRẢ HÀNG",
    "RETURN QTY": "SL TRẢ",
    "Rank": "Hạng",
    "Reason": "Lý do",
    "Reason (Details)": "Lý do (Chi tiết)",
    "Receipt note:": "Ghi chú phiếu:",
    "Receipt status:": "Trạng thái phiếu:",
    "Receipt type": "Loại phiếu",
    "Receipt type name": "Tên loại phiếu",
    "Refund Management": "Quản lý Hoàn tiền",
    "Reload": "Làm mới",
    "Remember Me": "Ghi nhớ",
    "Restore from File": "Khôi phục từ File",
    "Return Qty": "Số lượng trả",
    "Return Receipt List": "Danh sách Phiếu trả",
    "Return quantity must be a valid positive number.": "Số lượng trả phải là số dương hợp lệ.",
    "Return reason": "Lý do trả",
    "Return receipt created successfully!": "Tạo phiếu trả thành công!",
    "Revenue chart for the last 12 months": "Biểu đồ doanh thu 12 tháng qua",
    "Reward points": "Điểm thưởng",
    "Role": "Vai trò",
    "SKU": "SKU",
    "STATUS": "TRẠNG THÁI",
    "STORE ID": "MÃ CHI NHÁNH",
    "STORE NAME": "TÊN CHI NHÁNH",
    "SUPPLIER ID": "MÃ NCC",
    "SUPPLIER NAME": "TÊN NCC",
    "Sales Trends": "Xu hướng Bán hàng",
    "Sales invoice list from customers": "Danh sách hóa đơn bán hàng",
    "Sales quantity": "SL Bán",
    "Save": "Lưu",
    "Save Changes": "Lưu thay đổi",
    "Save changes": "Lưu thay đổi",
    "Save info": "Lưu thông tin",
    "Scan Barcode": "Quét Mã vạch",
    "Search": "Tìm kiếm",
    "Search ISBN, Book title...": "Tìm kiếm ISBN, Tên sách...",
    "Search Invoice": "Tìm Hóa đơn",
    "Search Order": "Tìm Đơn hàng",
    "Search by barcode, title...": "Tìm theo mã vạch, tên sách...",
    "Search by code, title, author...": "Tìm theo mã, tên, tác giả...",
    "Search by phone or name...": "Tìm theo số điện thoại hoặc tên...",
    "Search invoice ID...": "Tìm theo mã hóa đơn...",
    "Search invoice...": "Tìm hóa đơn...",
    "Search product (SKU, Name)...": "Tìm sản phẩm (SKU, Tên)...",
    "Search receipt ID...": "Tìm theo mã phiếu...",
    "Search receipt type...": "Tìm theo loại phiếu...",
    "Search shift...": "Tìm ca...",
    "Select": "Chọn",
    "Selling price": "Giá bán",
    "Shift closed successfully!": "Đóng ca thành công!",
    "Shift history": "Lịch sử ca",
    "Shift name": "Tên ca",
    "Shift started successfully!": "Bắt đầu ca thành công!",
    "Show": "Hiển thị",
    "Start": "Bắt đầu",
    "Start new shift": "Bắt đầu ca mới",
    "Start shift": "Bắt đầu ca",
    "Status": "Trạng thái",
    "Status:": "Trạng thái:",
    "Stock": "Tồn kho",
    "Stock warning": "Cảnh báo tồn kho",
    "Stock: ": "Tồn: ",
    "Store": "Chi nhánh",
    "Store ID / Code *": "Mã Chi nhánh *",
    "Store Management": "Quản lý Chi nhánh",
    "Store Name *": "Tên Chi nhánh *",
    "Store code already exists.": "Mã chi nhánh đã tồn tại.",
    "Success": "Thành công",
    "Supplier ID": "Mã NCC",
    "Supplier data not found!": "Không tìm thấy dữ liệu NCC!",
    "Supplier management": "Quản lý nhà cung cấp",
    "Supplier name (*)": "Tên NCC (*)",
    "Supplier name already exists!": "Tên NCC đã tồn tại!",
    "System Settings": "Cài đặt Hệ thống",
    "Title": "Tiêu đề",
    "Toggle between Light and Dark mode for the administrative interface.": "Chuyển đổi giữa chế độ Sáng và Tối.",
    "Total Return Qty: 0": "Tổng SL Trả: 0",
    "Total amount": "Tổng tiền",
    "Total merchandise": "Tổng tiền hàng",
    "Total refund amount: ": "Tổng tiền hoàn: ",
    "Trading": "Kinh doanh",
    "Trigger alert when quantity falls below this value.": "Báo động khi số lượng thấp hơn mức này.",
    "Type code": "Mã loại",
    "UNIT PRICE": "ĐƠN GIÁ",
    "Unit price": "Đơn giá",
    "Update Author": "Cập nhật Tác giả",
    "Update Category": "Cập nhật Danh mục",
    "Update Publisher": "Cập nhật NXB",
    "Update Supplier": "Cập nhật NCC",
    "Update error: ": "Lỗi cập nhật: ",
    "Update inventory": "Cập nhật kho",
    "Update successful!": "Cập nhật thành công!",
    "Use a scanner or manually enter invoice/product code.": "Sử dụng máy quét hoặc nhập mã hóa đơn/sản phẩm.",
    "Username": "Tên đăng nhập",
    "Vd: INV-2023...": "Vd: INV-2023...",
    "View book status at store.": "Xem trạng thái sách tại chi nhánh.",
    "Walk-in customer": "Khách vãng lai",
    "Warehouse": "Kho hàng",
    "Warning": "Cảnh báo",
    "Welcome back, here's what's happening with your store today.": "Chào mừng trở lại, đây là thông tin cửa hàng hôm nay.",
    "Working hours": "Giờ làm việc",
    "admin": "admin",
    "v2.4.0 (Stable)": "v2.4.0 (Stable)",
    "Ac 2024 Bookstore ERP": "© 2024 Bookstore ERP",
    "+ Add Customer": "+ Thêm Khách hàng",
    "+ Add Employee": "+ Thêm Nhân viên",
    "+ Add New": "+ Thêm Mới",
    "+ Add Store": "+ Thêm Chi nhánh",
    "+ Add User": "+ Thêm Người dùng",
    "+ CREATE NEW ORDER": "+ TẠO ĐƠN HÀNG MỚI",
    "+ Create Export Receipt": "+ Tạo Phiếu Xuất",
    "+ Create Import Receipt": "+ Tạo Phiếu Nhập",
    "+ Create Invoice": "+ Tạo Hóa Đơn",
    "+ Create Return Receipt": "+ Tạo Phiếu Trả",
    "Account Management": "Quản lý Tài khoản",
    "Account created successfully.": "Tạo tài khoản thành công.",
    "Account updated successfully.": "Cập nhật tài khoản thành công.",
    "Action": "Thao tác",
    "Active": "Hoạt động",
    "Active Status": "Trạng thái",
    "Add New": "Thêm mới",
    "Add New Author": "Thêm mới Tác giả",
    "Add New Category": "Thêm mới Danh mục",
    "Add New Publisher": "Thêm mới NXB",
    "Add New Supplier": "Thêm mới NCC",
    "Add new inventory": "Thêm mới kho",
    "Address": "Địa chỉ",
    "Address *": "Địa chỉ *",
    "Admin Terminal": "Giao diện Admin",
    "Admin User": "Người dùng Admin",
    "Admin manages document types for accounting/inventory.": "Admin quản lý loại chứng từ kế toán/kho.",
    "All Categories": "Tất cả Danh mục",
    "All Shifts": "Tất cả ca",
    "All Stores": "Tất cả Chi nhánh",
    "All Suppliers": "Tất cả Nhà cung cấp",
    "Any Role": "Tất cả Vai trò",
    "Any Status": "Mọi Trạng thái",
    "Are you sure you want to cancel this order? This action cannot be undone.": "Bạn có chắc chắn muốn hủy đơn hàng này không? Hành động này không thể hoàn tác.",
    "Are you sure you want to delete this category?": "Bạn có chắc chắn muốn xóa danh mục này?",
    "Are you sure you want to delete this customer?": "Bạn có chắc chắn muốn xóa khách hàng này?",
    "Are you sure you want to delete this product?": "Bạn có chắc muốn xóa sản phẩm này?",
    "Are you sure you want to delete this publisher?": "Bạn có chắc muốn xóa nhà xuất bản này?",
    "Are you sure you want to delete this receipt?": "Bạn có chắc chắn muốn xóa phiếu này không?",
    "Are you sure you want to delete this shift?": "Bạn có chắc chắn muốn xóa ca này?",
    "Are you sure you want to delete this store?": "Bạn có chắc chắn muốn xóa chi nhánh này?",
    "Are you sure you want to delete this supplier?": "Bạn có chắc muốn xóa nhà cung cấp này?",
    "Are you sure you want to delete this type?": "Bạn có chắc muốn xóa loại chứng từ này?",
    "Are you sure you want to delete this user?": "Bạn có chắc muốn xóa người dùng này?",
    "Author Name": "Tên Tác giả",
    "Author Management": "Quản lý Tác giả",
    "Author management": "Quản lý tác giả",
    "Author name (*)": "Tên Tác giả (*)",
    "Author: ": "Tác giả: ",
    "Authors": "Tác giả",
    "BACK": "QUAY LẠI",
    "BARCODE": "MÃ VẠCH",
    "BOOK TITLE": "TÊN SÁCH",
    "Back": "Quay lại",
    "Backup & Restore": "Sao lưu & Khôi phục",
    "Barcode": "Mã vạch",
    "Barcode is required.": "Vui lòng nhập mã vạch.",
    "Book List": "Danh sách Sách",
    "Book Title": "Tên Sách",
    "Business configuration and receipt settings.": "Cấu hình kinh doanh và thiết lập phiếu.",
    "Buy List": "Danh sách Mua",
    "Buy Qty": "Số lượng mua",
    "CATEGORY": "DANH MỤC",
    "CODE": "MÃ",
    "CONTACT": "LIÊN HỆ",
    "CREATED AT": "NGÀY TẠO",
    "CUSTOMER ID": "MÃ KHÁCH HÀNG",
    "CUSTOMER NAME": "TÊN KHÁCH HÀNG",
    "Cancel": "Hủy",
    "Cancel Order": "Hủy Đơn Hàng",
    "Cancel Order (F8)": "Hủy Đơn Hàng (F8)",
    "Canceled": "Đã hủy",
    "Cash": "Tiền mặt",
    "Catalog Management": "Quản lý Danh mục",
    "Categories": "Danh mục",
    "Category Name": "Tên Danh mục",
    "Category name (*)": "Tên danh mục (*)",
    "Category: ": "Danh mục: ",
    "Change Password": "Đổi Mật khẩu",
    "Choose shift": "Chọn ca",
    "Clear": "Xóa",
    "Clear list": "Xóa danh sách",
    "Close": "Đóng",
    "Close Shift": "Đóng ca",
    "Closed": "Đã đóng",
    "Code": "Mã",
    "Completed": "Hoàn thành",
    "Confirm Delete": "Xác nhận xóa",
    "Could not export empty data.": "Không thể xuất dữ liệu trống.",
    "Create Receipt": "Tạo Phiếu",
    "Create and manage user accounts and system roles.": "Tạo và quản lý tài khoản người dùng và vai trò.",
    "Current Store": "Chi nhánh hiện tại",
    "Customer": "Khách hàng",
    "Customer ID": "Mã Khách hàng",
    "Customer Management": "Quản lý Khách hàng",
    "Customer Name": "Tên Khách hàng",
    "Customer not found": "Không tìm thấy khách hàng",
    "DATE": "NGÀY",
    "DESCRIPTION": "MÔ TẢ",
    "Dashboard": "Tổng quan",
    "Data successfully exported to Excel!": "Xuất dữ liệu ra Excel thành công!",
    "Database backup & restore functionality for admin.": "Chức năng sao lưu & khôi phục DB cho admin.",
    "Date": "Ngày",
    "Date:": "Ngày:",
    "Delete": "Xóa",
    "Delete Category": "Xóa Danh mục",
    "Deleted successfully.": "Đã xóa thành công.",
    "Description": "Mô tả",
    "Details": "Chi tiết",
    "Discount": "Giảm giá",
    "Document Types": "Loại chứng từ",
    "Edit": "Sửa",
    "Email": "Email",
    "Email address": "Địa chỉ Email"
}

with open("c:/Users/ADMIN/Desktop/projects/university/BookStoreManagement/translate_dict_new.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print("Translation dictionary created.")
